use MER6;
select RESERVES.Data_reserva, VOL.Num_VOL, PASSATGER.Nom, PASSATGER.Cognom
FROM RESERVES, VOL, PASSATGER
WHERE PASSATGER.ID=RESERVES.ID AND VOL.ID=RESERVES.VOL_ID AND  PASSATGER.Nom="Laura";
