use MER4;
SELECT POLISSA.Num_polissa, TIPUS_POLISSA.Nom,
	CLIENT.DNI, CLIENT.Nom, CLIENT.Cognom
FROM CLIENT, POLISSA, TIPUS_POLISSA
WHERE CLIENT.DNI = POLISSA.CLIENT_DNI and
	TIPUS_POLISSA.ID = POLISSA.TIPUS_POLISSA_ID and
    TIPUS_POLISSA.Nom = "Viatge";