use MER7;
select  TICKET.Num_factura, TICKET.Data_ticket, EMPLEAT.Nom, EMPLEAT.Cognom
FROM TICKET, EMPLEAT, PRODUCTE, Linia_Ticket
WHERE PRODUCTE.ID=Linia_Ticket.PRODUCTE_ID AND
TICKET.ID= Linia_Ticket.TICKET_ID AND
EMPLEAT.ID=TICKET.EMPLEAT_ID AND
PRODUCTE.NOM="Jamon Serrano";
