use MER4;
SELECT CLIENT.Nom, CLIENT.Cognom, VENEDOR.Nom, VENEDOR.Cognom, POLISSA.Num_polissa, TIPUS_POLISSA.Nom
FROM CLIENT, VENEDOR, POLISSA, TIPUS_POLISSA
WHERE CLIENT.DNI = POLISSA.CLIENT_DNI and VENEDOR.DNI=POLISSA.VENDEDOR_DNI and POLISSA.TIPUS_POLISSA_ID=TIPUS_POLISSA.ID; 
